export const UPDATE_PROFILE_BASIC_USECASE = Symbol('UPDATE_PROFILE_BASIC');
export const UPDATE_PROFILE_BIO_USECASE = Symbol('UPDATE_PROFILE_BIO');
export const UPDATE_PROFILE_PORTFOLIO_USECASE = Symbol(
  'UPDATE_PROFILE_PORTFOLIO',
);
export const UPDATE_PROFILE_EXPERIENCE_USECASE = Symbol(
  'UPDATE_PROFILE_EXPERIENCE',
);
export const GET_SKILLS_USECASE = Symbol('GET_SKILLS');
export const GET_PROFILE_USECASE = Symbol('GET_PROFILE');
