export const GET_PROFILE_USECASE = Symbol('GET_PROFILE');
export const UPDATE_PROFILE_BASIC_USECASE = Symbol('UPDATE_PROFILE_BASIC');
export const UPDATE_PROFILE_BIO_USECASE = Symbol('UPDATE_PROFILE_BIO');
